title: LLM Artifacts
description: Documents emerging from conversations between humans and AI systems
theme: minima
markdown: kramdown

# Build settings
baseurl: ""
url: "https://liminalbardo.github.io/llm_artifacts"

# Hide footer
footer_col1: false
footer_col2: false
footer_col3: false
minima:
  social_links: []

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
